site_name: Fast AAPS - Documentación

nav:
    - 'Inicio': 'README.md'
    - 'FASTAAPS: Información General':
      - Mejoras del Sistema: 'FASTAAPS/upgrades.md'
      - (Docker) Contenerización de Servicios: 'FASTAAPS/docker.md'
      - Estándares de Calidad de Código: 'FASTAAPS/quality.md'
      - Instalación del Sistema en Servidores: 'FASTAAPS/deployment.md'
    - 'AAPS-LAB: Aplicaciones Interactivas': 
        - Resúmen: 'AAPS-LAB/summary.md'
    - 'AAPS-API: Servicio de Datos': 
        - Resúmen: 'AAPS-API/summary.md'
        - Servicios de Datos - Conceptos y Tecnologías: 'AAPS-API/general.md'
        - Especificación del Servicio de Datos: 'AAPS-API/specifications.md'
    - 'AAPS-AUTH: Seguridad':
        - Resúmen: 'AAPS-AUTH/summary.md'
        - Especificaciones de Seguridad: 'AAPS-AUTH/specifications.md'
    - 'AAPS-DATA: Sincronización y Almacenamiento de Datos': 
        - Resúmen: 'AAPS-DATA/summary.md'
        - Estándares y Especificaciones: 'AAPS-DATA/specifications.md'
        - Conjuntos de Datos: 'AAPS-DATA/dataset.md'
        - Servicio de Sincronización: 'AAPS-DATA/sync.md'
        - Base de Datos Especializada: 'AAPS-DATA/db.md'

theme:
  name: 'material'
  palette:
    primary: 'cyan'
    accent: 'cyan'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'blur_circular'
  language: 'es'
  favicon: 'assets/images/blur_circular.svg'


extra:
  search:
    language: 'es, en'
  social:
    - type: 'github'
      link: 'https://github.com/sergio-chumacero'
    - type: 'twitter'
      link: 'https://twitter.com/SergioChumacer1'

repo_name: 'sergio-chumacero/fastaaps'
repo_url: 'https://github.com/sergio-chumacero/fastaaps'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      separator: "_"
  - meta
  - pymdownx.superfences
  - pymdownx.details
  - footnotes